config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users#index"

  resources :caseloads, only: [:index]

  resources :users do
    resources :clients, except: [:show]
    resources :caseloads, only: [:show, :edit, :update]
  end

  get '/clients/unassigned', to: "clients#unassigned", as: "/clients/unassigned"

  get '/most-active-user', to: "users#most_active_user", as: "/most-active-user"

  resources :clients do
    resources :notes
  end

  resources :sessions, only: [:new, :create, :destroy]

  post '/signout', to: 'sessions#destroy', as: 'signout'

  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signin_with_google', to: redirect('/auth/google_oauth2'), as: 'signin_with_google'
  get 'register', to: "users#new", as: 'register'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')


end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :client
  validates :date, presence: true
  validates :length_in_minutes, presence: true, numericality: { only_integer: true }
  validates :content, length: { minimum: 75 }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :require_login
    before_action :set_client
    
    def index
    end

    def new
        @note = Note.new
    end

    def create
        @note = @client.notes.new(note_params)
        @note.user_id = current_user.id
        @note.save
        if @note.errors.any?
            render :new
        else
            redirect_to client_note_url(@client, @note)
        end
    end

    def show
        @note = @client.notes.find(params[:id])
        render json: @note
    end

    def edit
        @note = Note.find(params[:id])
        if authorized(@note.user)
            render :edit
        else
            flash[:error] = "You cannot edit another user's note."
            redirect_to client_note_url(@client, @note)
        end
    end

    def update
        @note = Note.find(params[:id])
        if authorized(@note.user)
            @note.update(note_params)
            redirect_to client_note_url(@client, @note)
        else
            flash[:error] = "You cannot update another user's note."
            redirect_to client_note_url(@client, @note)
        end
    end

    def destroy
        @note = Note.find(params[:id])
        if authorized(@note.user)
            @note.delete
            redirect_to client_notes_url(@client)
        else
            flash[:error] = "You cannot delete another user's note."
            redirect_to client_note_url(@client, @note)
        end
    end

    private

    def note_params
        params.require(:note).permit(:date, :length_in_minutes, :content, :user_id, :client_id)
    end

    def set_client
        @client = Client.find(params[:client_id])
    end

end

app/views/notes/_form.html.erb
<%= form_for [client, note] do |f| %>
    <%= f.label :date, "Date of Interaction" %>
    <%= f.date_field :date %><br>
    <%= f.label :length_in_minutes, 'Length of Interaction (in minutes)' %>
    <%= f.text_field :length_in_minutes %><br>
    <%= f.label :content, 'Content' %>
    <%= f.text_area :content %>

    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
    </button>
<% end %>

app/views/notes/edit.html.erb
<%= render partial: "form", locals: {client: @client, note: @note} %>   

app/views/notes/index.html.erb
<ul class="collection">
        <li class="collection-item"><strong>Notes for <%= link_to @client.name, @client %></strong></li>
        <% if @client.notes.empty? %>
                <li class="collection-item">No notes.  <%= link_to "Create one?", new_client_note_url(@client) %></li>
                </ul>
        <% else %>
                </ul>
                <ol class="collection">
                        <% @client.notes.each do |note| %>
                                <li class="collection-item"><%= link_to "#{note.date} note", client_note_path(@client, note) %> by <%= link_to note.user.name, user_path(note.user) %></li>
                        <% end %>
                </ol>
        <% end %>

app/views/notes/new.html.erb
<%= render partial: "form", locals: {client: @client, note: @note} %>   

app/views/notes/show.html.erb
<ul class="collection">
    <li class="collection-item"><h6><strong>Note for <%= @note.client.name %></strong></h6></li>
    <li class="collection-item">For interaction with <%= link_to @note.user.name, @note.user %> on <%= @note.date %></li>
    <li class="collection-item">Note first created on <%= @note.created_at %></li>
    <li class="collection-item">Note last updated on <%= @note.updated_at %></li>
    <li class="collection-item"><%= @note.length_in_minutes %> minutes</li>
    <li class="collection-item"><%= @note.content %></li>
</ul>

<%= link_to "Edit Note", edit_client_note_url(@note.client, @note), :class => "waves-effect waves-light btn" %>
<%= link_to "Delete Note", client_note_url(@note.client, @note), method: :delete, data: {confirm: "Are you sure?"}, :class => "waves-effect waves-light btn" %>