config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users#index"

  resources :caseloads, only: [:index]

  resources :users do
    resources :clients, except: [:show]
    resources :caseloads, only: [:show, :edit, :update]
  end

  get '/clients/unassigned', to: "clients#unassigned", as: "/clients/unassigned"

  get '/most-active-user', to: "users#most_active_user", as: "/most-active-user"

  resources :clients do
    resources :notes
  end

  resources :sessions, only: [:new, :create, :destroy]

  post '/signout', to: 'sessions#destroy', as: 'signout'

  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signin_with_google', to: redirect('/auth/google_oauth2'), as: 'signin_with_google'
  get 'register', to: "users#new", as: 'register'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :notes
    has_many :clients, through: :notes
    has_one :caseload

    before_save { self.email = email.downcase }
    validates :first_name, presence: true
    validates :last_name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
    validates :password, presence: true, length: { minimum: 6 }

    scope :most_active_user, -> { joins(:notes).select("users.*, count(notes.id) as ncount").group("users.id").order("ncount DESC").first }

    def name
        "#{self.first_name} #{self.last_name}"
    end

    def clients
        self.notes.map do |note|
            note.client
        end
    end

    def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.first_name = auth.info.first_name
			user.last_name = auth.info.last_name
            user.email = auth.info.email
            user.password = SecureRandom.urlsafe_base64
			user.save
		end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :new, :create]

    def index
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.errors.any?
            render :new
        else
            Caseload.create(user_id: @user.id)
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def most_active_user
        @user = User.most_active_user
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
    def logged_in?
        if session[:user_id]
        end
    end

    def current_user
        if logged_in?
            current_user ||= User.find(session[:user_id])
            return current_user
        end
    end
end

app/views/users/index.html.erb
<% if current_user %>
    <h6>Welcome to your home page, <%= current_user.name %>!</h6>
<% else %>
    <h6>Welcome! Register a new account or sign in!</h6>
<% end %>

app/views/users/most_active_user.html.erb
<ul class="collection">
    <li class="collection-item"><%= link_to "#{@user.name}", @user %> has the most notes.</li>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<div class="row">
    <div class="input-field col s6">
        First Name <%= f.text_field :first_name %>
        Last Name <%= f.text_field :last_name %>
        Email <%= f.email_field :email %>
        Password <%= f.password_field :password %>
        Confirm Password <%= f.password_field :password_confirmation %>
        <button class="btn waves-effect waves-light" type="submit" name="action">Register
            <i class="material-icons right">send</i>
        </button>
    </div>
</div>
<% end %>

app/views/users/show.html.erb
<ul class="collection">
<li class="collection-item"><%= link_to "Create a New Client", new_client_url %></li>
<li class="collection-item"><%= link_to "View All Clients", clients_url %></li>
<li class="collection-item"><%= link_to "View Clients without Case Manager Assignments", clients_unassigned_url %></li>
</ul>