config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users#index"

  resources :caseloads, only: [:index]

  resources :users do
    resources :clients, except: [:show]
    resources :caseloads, only: [:show, :edit, :update]
  end

  get '/clients/unassigned', to: "clients#unassigned", as: "/clients/unassigned"

  get '/most-active-user', to: "users#most_active_user", as: "/most-active-user"

  resources :clients do
    resources :notes
  end

  resources :sessions, only: [:new, :create, :destroy]

  post '/signout', to: 'sessions#destroy', as: 'signout'

  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signin_with_google', to: redirect('/auth/google_oauth2'), as: 'signin_with_google'
  get 'register', to: "users#new", as: 'register'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')


end

app/models/client.rb
class Client < ApplicationRecord
    has_many :notes
    has_many :users, through: :notes
    belongs_to :caseload, optional: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    scope :unassigned, -> { where(caseload_id: nil) }

    def name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :require_login
    before_action :set_client, only: [:edit, :update, :show]
    
    def index
        @clients = Client.all
    end

    def new
        @client = Client.new
    end

    def create
        @client = Client.new(client_params)
        if @client.save
            render json: @client
        else
            render :new
        end
    end

    def edit
        if @client.caseload.nil? || (@client.caseload && authorized(@client.caseload.user))
            render :edit
        else
            flash[:error] = "You cannot edit another user's client."
            redirect_to client_url(@client)
        end
    end

    def update
        if @client.caseload.nil? || (@client.caseload && authorized(@client.caseload.user))
            if @client.update(client_params)
                redirect_to client_path(@client)
            else
                render :edit
            end
        else
            flash[:error] = "You cannot update another user's client."
            redirect_to client_url(@client)
        end
    end

    def show
        respond_to do |format|
            format.html
            format.json { render json: @client }
        end
    end

    def unassigned
        @clients = Client.unassigned
    end

    private

    def client_params
        params.require(:client).permit(:first_name, :last_name, :caseload_id)
    end

    def set_client
        @client = Client.find(params[:id])
    end

end

app/views/clients/_form.html.erb
<%= form_for(@client, :html => {:id => "client_form"}) do |f| %>
    <div class="input-field col s12">
    <%= f.label :first_name, "First Name" %><br />
    <%= f.text_field :first_name %>
  </div>
  
  <div class="input-field col s12">
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name %>
  </div>

  <%= f.label :case_manager, "Case Manager" %>
  <%= f.collection_select(:caseload_id, Caseload.all, :id, :case_manager, { :include_blank => true }, { :class => 'browser-default' }) %>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>

<% end %>

app/views/clients/_list.html.erb
<ul class="collection">
<% @clients.sort_by(&:name).each do |client| %>
    <li class="collection-item"><%= link_to "#{client.name}", client %></li>
<% end %>
</ul>

app/views/clients/edit.html.erb
<%= render partial: "form", locals: {client: @client} %>

app/views/clients/index.html.erb
<%= render partial: "list", locals: {clients: @clients} %>

app/views/clients/new.html.erb
<%= form_for @client do |f| %>
    <div class="input-field col s12">
    <%= f.label :first_name, "First Name" %><br />
    <%= f.text_field :first_name %>
  </div>
  
  <div class="input-field col s12">
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name %>
  </div>

  <%= f.label :case_manager, "Case Manager" %>
  <%= f.collection_select(:caseload_id, Caseload.all, :id, :case_manager, { :include_blank => true }, { :class => 'browser-default' }) %>
  <button class="btn waves-effect waves-light" type="submit" name="action">Create Client
    <i class="material-icons right">send</i>
  </button>

<% end %>

app/views/clients/show.html.erb
<ul class="collection">
    <li class="collection-item"><h6><strong><%= @client.name %></strong></h6></li>
    <% if @client.caseload %>
        <li class="collection-item">Case Manager: <%= link_to @client.caseload.user.name, user_caseload_url(@client.caseload) %></li>
    <% else %>
        <li class="collection-item">Case Manager: Unassigned</li>
    <% end %>
    <li class="collection-item"><%= link_to "Client Notes", client_notes_url(@client) %></li>
    <li class="collection-item"><%= link_to "Edit Client Information", edit_client_url(@client) %></li>
</ul>

app/views/clients/unassigned.html.erb
<%= render partial: "list", locals: {clients: @clients} %>