config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users#index"

  resources :caseloads, only: [:index]

  resources :users do
    resources :clients, except: [:show]
    resources :caseloads, only: [:show, :edit, :update]
  end

  get '/clients/unassigned', to: "clients#unassigned", as: "/clients/unassigned"

  get '/most-active-user', to: "users#most_active_user", as: "/most-active-user"

  resources :clients do
    resources :notes
  end

  resources :sessions, only: [:new, :create, :destroy]

  post '/signout', to: 'sessions#destroy', as: 'signout'

  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signin_with_google', to: redirect('/auth/google_oauth2'), as: 'signin_with_google'
  get 'register', to: "users#new", as: 'register'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Case Manager on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'caseloads' %>
    <%= javascript_include_tag 'client' %>
  </head>

  <body>
    <nav class="nav-extended">
      <div class="nav-wrapper">
      <a href="/" class="brand-logo">Case Manager on Rails</a> 
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if current_user %>
          <li>
            <%= link_to("Sign Out", signout_url, method: :post) %>
          </li>
          <% else %>
          <li>
            <%= link_to "Register", register_url %>
          </li>
          <li>
            <%= link_to "Sign In", signin_url %>
          </li>
            <% end %>
        </ul>
      </div>
      <% if current_user %>
      <div class="nav-content">
        <ul class="tabs tabs-transparent">
          <li class="tab"><%= link_to "My Account", current_user %></li>
          <li class="tab"><%= link_to "My Caseload", user_caseload_url(current_user, current_user.caseload) %></li>
          <li class="tab"><%= link_to "All Caseloads", caseloads_url, class: "all_caseloads" %></li>
        </ul>
      </div>
      <% end %>
    </nav>
    <div id="app-container">
    <%= yield %>


    <% if @user && @user.errors.any? %>
      <ul class="collection">
        <li class="collection-item">One or more errors occurred:</li>
        <% @user.errors.full_messages.each do |message| %>
          <li class="collection-item"><%= message %></li>
        <% end %>
      </ul>
    <% elsif @note && @note.errors.any? %>
      <ul class="collection">
      <li class="collection-item">One or more errors occurred:</li>
        <% @note.errors.full_messages.each do |message| %>
          <li class="collection-item"><%= message %></li>
        <% end %>
      </ul>
    <% elsif @client && @client.errors.any? %>
      <ul class="collection">
      <li class="collection-item">One or more errors occurred:</li>
        <% @client.errors.full_messages.each do |message| %>
          <li class="collection-item"><%= message %></li>
        <% end %>
      </ul>
    <% end %>


    <% if flash[:error] %>
      <ul class="collection">
        <li class="collection-item">One or more errors occurred:</li>
        <li class="collection-item"><%= flash[:error] %></li>
      </ul>
    <% end %>
  </div>
  </body>
</html>
  